name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.11.0

      # 3. Installation des dépendances backend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      # 4. Lancement des tests backend
      - name: Run backend tests
        run: npm test
        working-directory: ./backend

      # 5. Build de l'image Docker backend
      - name: Build Docker image
        run: docker build -t hindamraoui/user-management-app-backend ./backend

      # 6. Push de l'image vers Docker Hub
      - name: Login to Docker Hub
        run: echo "Amraouihind2003" | docker login -u "hindamraoui" --password-stdin

      - name: Push Docker image
        run: docker push hindamraoui/user-management-app-backend

      # 7. (Optionnel) Déploiement via SSH (ex : VPS Contabo)
      # - name: Deploy to VPS via SSH
      #   if: ${{ secrets.SSH_PRIVATE_KEY }}
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker pull hind/user-management-app-backend
      #       docker stop backend || true
      #       docker rm backend || true
      #       docker run -d --name backend -p 3000:3000 hind/user-management-app-backend
